# Generated by Django 4.2.3 on 2023-09-06 14:43

from django.db import migrations, models
import news.models.news_model


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0003_news"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="title",
            field=models.CharField(
                max_length=200,
                validators=[news.models.news_model.validate_not_single_word],
            ),
        ),
    ]
